### PR TITLE
Update to fix the plugin!

### PR DESCRIPTION
**Pull request by GoldCodes**
I fixed the plugin so I hope you enjoy!

### CODE REVIEW

**Comment by xZeroMCPE** [comment]
Have you tested this?

**Comment by GoldCodes** [comment]
Still cleaning it up!

**Comment by GoldCodes** [comment]
It is curently having problems with adding arenas

**Comment by GoldCodes** [comment]
Signs are also broken

**Comment by xZeroMCPE** [comment]
Any errors

**Comment by kabluinc** [comment]
When can this be fixed?

**Comment by ghost** [comment]
This is already added!

**Pull request closed without merging**
