### PR TITLE
Improved Spanish translation

### PR DESCRIPTION
**Pull request by Khristian-kun**
I wanted to help because it was made by a translator. Next time ask for a native spanish for translate :)

### CODE REVIEW

**Comment by xZeroMCPE** [comment]
Thanks :)

**Comment by Khristian-kun** [comment]
Your welcome :)

**Comment by Khristian-kun** [comment]
But i have to fix some errors i did, let me make another pull request :(

**Comment by xZeroMCPE** [comment]
ok lol

**Pull request merged**
