### PR TITLE
fix #10

### LINKED ISSUE #10: save config
[CRITICAL]: Could not save Config /Users/Ronny/Desktop/Catching Fire/plugins/SurvivalGame/config.yml: file_put_contents(/Users/Ronny/Desktop/Catching Fire/plugins/SurvivalGame/config.yml): failed to open stream: No such file or directory

### PR DESCRIPTION
**Pull request by dries-c**

### CODE REVIEW

**Comment by xZeroMCPE** [comment]
Thank, It has been merge with my code.

**Comment by dries-c** [comment]
you dont merge it

**Comment by xZeroMCPE** [comment]
I just did now,

**Comment by dries-c** [comment]
Ok

Dries C
Op 23-dec.-2015 21:09 schreef "Andre" notifications@github.com:

**Pull request closed without merging**
