### PR TITLE
Fixed $arena

### PR DESCRIPTION
**Pull request by Taki21**
Before was $arena ==
Thats for if statements lol
its $arena = blahblahblah

### CODE REVIEW

**Comment by Taki21** [comment]
TESTED->Error Still There...

**Comment by xZeroMCPE** [comment]
Somehow the plugin doesn't load the default config. I have no idea why? Anyway the $arena issue is fixed. But still need to find a way to make the plugin load the config i already made.

**Comment by Taki21** [comment]
xD 
$this->saveDefaultConfig()

**Comment by Taki21** [comment]
Wait....Add my code it works! I just tried again...

**Comment by xZeroMCPE** [comment]
Seems to be working. But plugins seem not to be loading the default config i've made. It just created it own config.

**Comment by Taki21** [comment]
Ik.  New Version has been doin that

**Comment by xZeroMCPE** [comment]
Anyway, i'm still figuring out how to make it load my config.

**Pull request merged**
